#!/system/bin/sh

#####
# This file is part of the Mounts2SD Project: https://github.com/spazedog/mounts2sd
#  
# Copyright (c) 2013 Daniel Bergløv
#
# Mounts2SD is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Mounts2SD is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Mounts2SD. If not, see <http://www.gnu.org/licenses/>
#####

scriptAction=$1
scriptVersion="5.5.0"
scriptProps="script=1 move_apps=1 move_dalvik=0 move_data=0 enable_reversed_mount=0 enable_cache=2 no_tmpfs_cache=0 enable_swap=1 set_swap_level=0 enable_sdext_journal=0 enable_debug=1 set_sdext_fstype=ext4 set_sdcard_readahead=512 run_sdext_fschk=1 disable_safemode=0 disable_cache_folders=0"
bb=/system/xbin/busybox
tb=/system/bin/toolbox

doProp() {
    doPropAction="$1"
    doPropName="$2"
    doPropValue="$3"

    case "$doPropAction" in
        "set")
            if $bb [ ! -z "$doPropName" ]; then
                $bb echo "$doPropValue" > /props/$doPropName
                $bb chmod 0660 /props/$doPropName
                $bb chown 1000.1000 /props/$doPropName
            fi
        ;;

        "get")
            if $bb [ ! -z "$doPropName" ]; then
                $bb [ -f /props/$doPropName ] && $bb cat /props/$doPropName || $bb echo $doPropValue
            fi
        ;;

        "remove")
            if $bb [ ! -z "$doPropName" ]; then
                $bb [ -f /props/$doPropName ] && $bb rm -rf /props/$doPropName
            fi
        ;;
    esac
}

doLog() {
    if $bb [ "$1" != "d" ] || $bb [ $(doProp get config.enable_debug 0) -eq 1 ]; then
        doLi=0
        doLogParts=

        for doLx; do
            doLi=$(($doLi + 1))

            case "$doLi" in
                "1") doLogLevel="$doLx" ;;
                "2") doLogLogger="$doLx" ;;
                "3") 
                    doLogTemplate="$doLx"
                    doLogMessage="$doLogTemplate" 
                ;;

                *)  
                    doLogMessage="`$bb echo $doLogMessage | $bb sed "s/\%arg$(($doLi - 3))/$($bb echo $doLx | $bb sed 's/\//\\\\\//g')/g"`"

                    $bb [ -z "$doLogParts" ] && doLogParts="$doLx" || doLogParts="${doLogParts}ad4ebc50/$doLx"
                ;;
            esac
        done

        doLogEntry="${doLogLevel}883b21e9/${doLogLogger}883b21e9/${doLogTemplate}883b21e9/$doLogParts"

        log -p $doLogLevel -t "Mounts2SD" "$doLogMessage"

        $bb echo "$doLogEntry" >> /props/log
    fi
}

doCreateFolder() {
    $bb [ "$2" = "1" ] && doCFFolder="$1 $($bb echo $1 | $bb sed -e 's/^\/[^\/]*\//\/sd-ext\//')" || doCFFolder="$1"
    doCFCh=0

    for doCFx in $doCFFolder; do
        if $bb [ ! -d $doCFx ]; then
            doLog d script "Function: Creating folder %arg1!" $doCFx
            $bb mkdir $doCFx

            doCFCh=1
        fi
    done

    if $bb [ $doCFCh -eq 1 ]; then
        doSetPerms "$doCFFolder" 1000.1000 0771
    fi
}

doSetPerms() {
    doSPFolder="$1"
    doSPOwner="$2"
    doSPPerm="$3"
    
    for doSPi in $doSPFolder; do
        for doSPx in /*.rc; do
            doSPBuildIn="$($bb grep mkdir $doSPx | $bb grep -ve '^[ \t]*#' | $bb grep " $doSPi " | $bb tail -n1)"

            if $bb [ ! -z "$doSPBuildIn" ]; then
                doSPOwnerTmp="$($bb echo $doSPBuildIn | $bb awk '{print $4}').$($bb echo $doSPBuildIn | $bb awk '{print $5}')"
                doSPPermTmp="$($bb echo $doSPBuildIn | $bb awk '{print $3}')"

                $bb [ "$doSPOwnerTmp" != "." ] && doSPOwner="$doSPOwnerTmp"
                $bb [ ! -z "$doSPPermTmp" ] && doSPPerm="$doSPPermTmp"

                break
            fi
        done

        break
    done

    if $bb [ -z "$cmdCH" ]; then
        $tb chown 2> /dev/null
        doSPStatus=$?

        # Busybox cannot always set owners based on names, so we use toolbox whenever we can.
        # However not all toolbox versions has chmod and chown included.
        if $bb [ "$doSPStatus" = "255" ]; then
            export cmdCH="$bb"
        else
            export cmdCH="$tb"
        fi
    fi

    for doSPi in $doSPFolder; do
        doLog d script "Function: Changing permissions on %arg1 to %arg2:%arg3!" $doSPi $doSPOwner $doSPPerm

        $cmdCH chmod $doSPPerm $doSPi
        $cmdCH chown $doSPOwner $doSPi 
    done
}

doGetSize() {
    doGetSizePartition=$1
    doGetSizeX=1

    for i in `$bb df -m $doGetSizePartition | $bb tail -n1`; do
        if $bb [ -z "`$bb echo $i | $bb sed -e 's/[0-9]*//'`" ]; then
            if [ $doGetSizeX -eq 3 ]; then
                echo $i; break
            fi

            doGetSizeX=$(($doGetSizeX + 1))
        fi
    done
}

doCheckFolder() {
    doCheckFolderPath=$1
    doCheckFolderValue=0

    for doCheckFolderX in /*.rc; do
        if $bb [ ! -z "`$bb grep mkdir $doCheckFolderX | $bb grep -ve '^[ \t]*#' | $bb grep -e " $doCheckFolderPath\(\/\)* "`" ]; then
            doCheckFolderValue=1; break
        fi
    done

    echo $doCheckFolderValue
}

doKillSystemServer() {
    while :; do
        $bb killall system_server 2>/dev/null

        $bb sleep 3
    done
}

# This is used as a hack to break out of at any time
for loopwrapper in true; do

	# ===========================================================================================
	# -------------------------------------------------------------------------------------------
	# USE SOME VERY BASIC SHELL SYNTAX TO TEST FOR THE EXISTENCE OF BUSYBOX
	# 

	$bb test 2> /dev/null

	# This is a hacked way of checking whether or not busybox exists.
	# Some toolbox versions are so limited that they don't even support basic echo command, and most are missing things like [ to make proper conditional checks using if and else.
	case "$?" in
		"1") 
            if $bb [ "52223abccbcf00eb3c81300545d63126" != "`( $bb [ 1 -eq 0 ] || $bb [ 0 -eq 1 ] ) && $bb echo no || $bb echo 'remove this part okay:bla=no-4' | $bb grep -e '.*bla=no-[1-9]*' | $bb sed -e 's/^remove //' | $bb awk '{print $3}' | $bb cut -d ':' -f1 | md5sum | $bb awk '{print $1}'`" ]; then
                $tb log -p e -t mounts2sd "The current busybox version is to old or limited to be used with Mounts2SD!"

                break
            fi
        ;;

		*)
			$tb log -p e -t mounts2sd "No busybox binary is present on the device!"

			# Break $loopwrapper
			break
		;;
	esac

	# ===========================================================================================
	# -------------------------------------------------------------------------------------------
	# MAKE SURE THAT WE HAVE ROOT PERMISSIONS AS THIS SCRIPT MAY ALSO BE INVOKED VIA THE APP
	# 

    if $bb [ "`$bb id | $bb sed -ne "s/^uid=\([0-9]*\)[^0-9].*$/\1/p"`" != "0" ]; then
        doLog e script "M2SD has been invoked without superuser permissions!"; break
    fi

	# ===========================================================================================
	# -------------------------------------------------------------------------------------------
	# LETS EXECUTE THE SCRIPT OPERATIONS
	# 
    case "$scriptAction" in
        "version")
            $bb echo $scriptVersion
        ;;

        *)
	        modRoot="`$bb grep ' / ' /proc/mounts | $bb sed 's/.*[ ,]\(r[ow]\)[ ,].*/\1/'`"
	        modSystem="`$bb grep ' /system ' /proc/mounts | $bb sed 's/.*[ ,]\(r[ow]\)[ ,].*/\1/'`"

	        $bb [ "$modRoot" != "rw" ] && $bb mount -o remount,rw /
	        $bb [ "$modSystem" != "rw" ] && $bb mount -o remount,rw /system

            doCreateFolder /props

            if $bb [ -e /data/property/m2sd.script ] && $bb [ "`$bb cat /data/property/m2sd.script`" = "0" ]; then
                doLog v script "M2SD is disabled. Canceling!"; break

            else
                case "$scriptAction" in
                    "finalize")
                        # Used by safe-mode in order to allow the first part to finish before the second part is executed
                        if $bb [ $(doProp get status.script 0) -eq 2 ]; then
                            for countdown in `$bb seq 1 10`; do
                                $bb sleep 1

                                if $bb [ $(doProp get status.script 0) -lt 2 ]; then
                                    break
                                fi
                            done
                        fi

                        if $bb [ $(doProp get status.script 0) -eq 0 ]; then
                            doLog e script "The script has not been fully executed during boot!"

                        else
                            # Do some final stuff to help with the Android app installation problems
                            doLog v script "Executing the final steps of the script"
                            doLog d script "Looking for the sqlite3 binary to change the storage threshold"
		                    if $bb [ -e /data/data/com.android.providers.settings/databases/settings.db ] && $bb [ ! -z "`$bb which sqlite3`" ]; then
                                i=0;

			                    while :
			                    do
				                    value=$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "select value from secure where name = 'sys_storage_threshold_percentage'" 2>&1)
                                    status=$?
				
				                    if $bb [ $status -eq 0 ]; then
                                        doLog v script "Storage threshold is set to %arg1" 1%

					                    if $bb [ -z "$value" ] || $bb [ "$value" != "1" ]; then
						                    value=$(sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into secure (name, value) VALUES('sys_storage_threshold_percentage','1')" 2>&1)
						                    sqlite3 /data/data/com.android.providers.settings/databases/settings.db "insert into gservices (name, value) VALUES('sys_storage_threshold_percentage','1')"
					                    fi
					
					                    break
				                    fi

                                    if $bb [ $i -gt 9 ]; then
                                        doLog w script "Storage threshold not changed. The Sqlite3 binary returns result code '%arg1'!" $status

                                        if $bb [ ! -z "$lastError" ]; then
                                            doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                        fi

                                        break
                                    fi

                                    i=$(($i + 1))

				                    sleep 1
			                    done

                            elif $bb [ -z "`$bb which sqlite3`" ]; then
                                doLog v script "Storage threshold not changed. Sqlite3 binary is missing!"
		                    fi
                        fi
                    ;;

                    *)
                        if $bb [ $(doProp get status.script 0) -gt 0 ]; then
                            break
                        fi

                        for i in /sd-ext /data/property; do
                            doCreateFolder $i
                        done

                        if $bb [ ! -d /props ]; then
                            doLog e script "Could not write to the tmpfs ramdisk!"; break
                        fi

                        doLog v script "Preparing configurations"

                        doProp set status.script 2

                        for i in $scriptProps; do
                            iName="`$bb echo $i | $bb cut -d '=' -f1`"

                            if $bb [ ! -e /data/property/m2sd.$iName ]; then
                                doLog d script "Creating missing property %arg1" /data/property/m2sd.$iName
                                $bb echo $($bb echo $i | $bb cut -d '=' -f2) > /data/property/m2sd.$iName
                            fi
                        done

                        # We use this for both r-mount protection and for later status review
                        for i in /data/property/m2sd.*; do
                            doLog d script "Moving property %arg1 into %arg2" "$($bb basename $i)='$($bb cat $i)'" /props/
                            doProp set config.$($bb echo $($bb basename $i) | $bb sed "s/^m2sd\.//") $($bb cat $i)
                        done

                        cmdPS=$($bb which ps || echo "$bb ps")

                        $bb sleep 1

                        if $bb [ ! -z "`$cmdPS | $bb grep /system/bin/servicemanager`" ]; then
                            if $bb [ $(doProp get config.disable_safemode 0) -eq 0 ]; then
                               if $bb [ $(doProp get config.enable_reversed_mount 0) -eq 1 ]; then
                                   if $bb [ $(doProp get config.move_apps 0) -eq 1 ]; then
                                       $bb echo 0 > /data/property/m2sd.move_apps
                                       $bb echo 0 > /props/config.move_apps
                                   else
                                       $bb echo 1 > /data/property/m2sd.move_apps
                                       $bb echo 1 > /props/config.move_apps
                                   fi
                               fi

                               for i in move_dalvik move_data enable_reversed_mount; do
                                   doLog d script "/system/bin/servicemanager is running, disabling property %arg1 to prepare safe-mode" /data/property/m2sd.$i
                                   $bb echo 0 > /data/property/m2sd.$i
                                   $bb echo 0 > /props/config.$i
                               done

                               doLog i script "The script is running in safe-mode!"
                               doProp set status.script_safe_mode 1

                            elif $bb [ $(doProp get config.disable_safemode 0) -gt 0 ]; then
                                # doLog v script "Safe-mode has been disabled, skipping init.d test!"

                                doLog v script "/system/bin/servicemanager is running, Stalling System Server"

                                doKillSystemServer & 

                                export doKillPid=$!
                            fi
                        fi

                        doLog v script "Waiting for sdcard to initiate"

                        for mmcTries in `$bb seq 1 8`; do
                            doLog d script "Preparing try number %arg1 for locating the sdcard" $mmcTries

                            for mmcNum in `$bb seq 0 9`; do
                                if $bb [ -e /sys/block/mmcblk$mmcNum/device/type ]; then
                                    doLog d script "Checking device type on %arg1" /sys/block/mmcblk$mmcNum
                                fi
                        
                                if $bb [ -e /sys/block/mmcblk$mmcNum/device/type ] && [ "`$bb cat /sys/block/mmcblk$mmcNum/device/type`" = "SD" ]; then
                                    mmcDevcie=/dev/block/mmcblk$mmcNum && doProp set status.device.sdcard $mmcDevcie
                                    mmcMM=$($bb ls -l $mmcDevcie | $bb tr -s " " | $bb sed -ne "s/^.*[ ]\([0-9]*\),[ ]\([0-9]*\)[ ].*$/\1:\2/p") && doProp set device.sdcard.mm $mmcMM

                                    doLog v script "The sdcard device was located at %arg1" $mmcDevcie
                                    doLog d script "The sdcard MM number was located at %arg1" $mmcMM

                                    if $bb [ -e /sys/devices/virtual/bdi/$mmcMM/read_ahead_kb ]; then
                                        rhValue=$(doProp get config.set_sdcard_readahead 512)

                                        doLog v script "Setting sdcard readahead to %arg1" ${rhValue}Kb

                                        $bb echo $rhValue > /sys/devices/virtual/bdi/$mmcMM/read_ahead_kb

                                        if $bb [ "$rhValue" != "`$bb cat /sys/devices/virtual/bdi/$mmcMM/read_ahead_kb`" ]; then
                                            doLog w set_sdcard_readahead "Could not set the sdcard readahead!"
                                        fi

                                        doProp set status.set_sdcard_readahead $($bb cat /sys/devices/virtual/bdi/$mmcMM/read_ahead_kb)

                                    else
                                        doLog d script "Did not locate the sdcard readahead device file at %arg1" /sys/devices/virtual/bdi/$mmcMM/read_ahead_kb
                                    fi

                                    doLog v script "Checking sdcard partitions"

                                    for i in `$bb seq 1 3`; do
                                        doLog d script "Looking for device file %arg1" ${mmcDevcie}p${i}

                                        if $bb [ -e ${mmcDevcie}p${i} ]; then
                                            case "$i" in
                                                "1")
                                                    doLog v script "Using %arg1 as %arg2" ${mmcDevcie}p${i} "fat32 (sdcard)"
                                                    doProp set status.device.sdcard.partition.vfat "${mmcDevcie}p${i}"
                                                ;;

                                                "2")
                                                    mmcExternalFs=$(doProp get config.set_sdext_fstype ext4)

                                                    doLog v script "Using %arg1 as %arg2" ${mmcDevcie}p${i} "$mmcExternalFs (sd-ext)"
                                                    doProp set status.device.sdcard.partition.sdext "${mmcDevcie}p${i}"

                                                    if $bb [ ! -z "$mmcExternalFs" ] && $bb [ "$mmcExternalFs" != "auto" ] && $bb [ -z "`$bb grep $mmcExternalFs /proc/filesystems | $bb grep -v 'nodev'`" ]; then
                                                        doLog w set_sdext_fstype "The sd-ext filesystem type %arg1 is not supported. Switched to auto detection!" $mmcExternalFs
                                                        mmcExternalFs="auto"
                                                    fi

                                                    doProp set status.set_sdext_fstype $mmcExternalFs
                                                ;;

                                                "3")
                                                    doLog v script "Using %arg1 as %arg2" ${mmcDevcie}p${i} SWAP
                                                    doProp set status.device.sdcard.partition.swap "${mmcDevcie}p${i}"
                                                ;;
                                            esac
                                       
                                        else
                                            doLog d script "Device file %arg1 does not exist" ${mmcDevcie}p${i}
                                        fi
                                    done

                                    if $bb [ -z "$(doProp get status.device.sdcard.partition.sdext)" ]; then
                                        doLog w script "The sd-ext partition could not be located!"; break 2

                                    elif $bb [ ! -z "`$bb cat /proc/mounts | $bb grep -w $(doProp get status.device.sdcard.partition.sdext)`" ]; then
                                        doLog w script "The sd-ext device %arg1 is already in use by another script!" $(doProp get status.device.sdcard.partition.sdext); break 2
                                    fi

                                    if $bb [ $(doProp get config.run_sdext_fschk) -eq 1 ]; then
                                        if $bb [ ! -z "`$bb which e2fsck`" ]; then
                                            doLog v script "Running file system check on sd-ext"
                                            doProp set status.run_sdext_fschk 1

                                            lastError=$(e2fsck -y -D $(doProp get status.device.sdcard.partition.sdext) 2>&1)

                                            status=$?

                                            if $bb [ $status -gt 0 ] && $bb [ $status -lt 4 ]; then
                                                    doLog i run_sdext_fschk "Error detected while checking sd-ext. Auto correction was performed!"

                                            elif $bb [ $status -gt 0 ]; then
                                                    doLog w run_sdext_fschk "Error detected while checking sd-ext. Everything was left uncorrected!"

                                                    if $bb [ ! -z "$lastError" ]; then
                                                        doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                    fi
                                            fi

                                        else
                                            doLog w run_sdext_fschk "Could not do a file system check on sd-ext. Missing e2fsck!"
                                            echo 0 > /data/property/m2sd.run_sdext_fschk
                                        fi

                                    else
                                        doLog d script "File system check is disabled, skipping"
                                    fi

                                    doLog v script "Setting optimized mount parameters on sd-ext"

                                    if $bb [ "`doProp get status.set_sdext_fstype`" = "ext4" ]; then
                                        doLog d script "%arg1 file system detected, checking journal settings" Ext4

                                        if $bb [ ! -z "`$bb which tune2fs`" ]; then
                                            if [ $(doProp get config.enable_sdext_journal) -lt 2 ]; then
                                                if $bb [ $(doProp get config.enable_sdext_journal) -eq 0 ]; then
                                                    if $bb [ ! -z "`tune2fs -l $(doProp get status.device.sdcard.partition.sdext) | $bb grep features | $bb grep has_journal`" ]; then
                                                        doLog v script "Disabling %arg1 journal on sd-ext" ext4
                                                        lastError=$(tune2fs -O ^has_journal $(doProp get status.device.sdcard.partition.sdext) 2>&1)

                                                        status=$?

                                                        if $bb [ $status -gt 0 ]; then
                                                                doLog e enable_sdext_journal "Error while trying to turn off sd-ext %arg1 journal!" ext4

                                                                if $bb [ ! -z "$lastError" ]; then
                                                                    doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                                fi

                                                        elif $bb [ ! -z "`tune2fs -l $(doProp get status.device.sdcard.partition.sdext) | $bb grep features | $bb grep has_journal`" ]; then
                                                            doLog w enable_sdext_journal "Could not turn off the sd-ext %arg1 journal!" ext4
                                                        fi
                                                    fi

                                                else
                                                    if $bb [ -z "`tune2fs -l $(doProp get status.device.sdcard.partition.sdext) | grep features | grep has_journal`" ]; then
                                                        doLog v script "Enabling %arg1 journal on sd-ext" ext4
                                                        tune2fs -O has_journal $(doProp get status.device.sdcard.partition.sdext)

                                                        status=$?

                                                        if $bb [ $status -gt 0 ]; then
                                                                doLog e enable_sdext_journal "Error while trying to turn on sd-ext %arg1 journal!" ext4

                                                                if $bb [ ! -z "$lastError" ]; then
                                                                    doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                                fi

                                                        elif $bb [ -z "`tune2fs -l $(doProp get status.device.sdcard.partition.sdext) | $bb grep features | $bb grep has_journal`" ]; then
                                                            doLog w enable_sdext_journal "Could not turn on the sd-ext %arg1 journal!" ext4
                                                        fi
                                                    fi
                                                fi

                                            else
                                                doLog d script "Journal settings is set to auto. Keeping default settings"
                                            fi

                                            $bb [ -z "`tune2fs -l $(doProp get status.device.sdcard.partition.sdext) | $bb grep features | $bb grep has_journal`" ] && doProp set status.enable_sdext_journal 0 || doProp set status.enable_sdext_journal 1

                                        else
                                            if $bb [ $(doProp get config.enable_sdext_journal) -lt 2 ]; then
                                                doLog w enable_sdext_journal "Could not handle the %arg1 journal. Missing tune2fs!" ext4
                                                echo 2 > /data/property/m2sd.enable_sdext_journal

                                            else
                                                doLog i enable_sdext_journal "Could not handle the %arg1 journal. Missing tune2fs!" ext4
                                            fi
                                        fi

                                    elif $bb [ "`doProp get status.set_sdext_fstype`" = "ext3" ]; then
                                        doLog d script "%arg1 file system detected, checking journal settings" Ext3

                                        if [ $(doProp get config.enable_sdext_journal) -eq 0 ]; then
                                            doLog v script "Setting parameter to disable %arg1 journal" ext3
                                            doProp set status.enable_sdext_journal 0
                                            mountParamsExtras="noload"

                                        else
                                            doLog d script "Journal settings is not set to disable, keeping journal enabled"
                                            doProp set status.enable_sdext_journal 1
                                        fi
                                    fi

                                    doProp set status.destination.external /sd-ext

                                    if $bb [ $(doProp get config.enable_reversed_mount) -eq 1 ]; then 
                                        doLog v script "R-mount is enabled, moving the internal data mount point to /sd-ext"

                                        lastError=$($bb mount --move /data /sd-ext 2>&1)

                                        if $bb [ -z "`$bb grep ' /sd-ext ' /proc/mounts`" ]; then
                                            doLog d script "Moving Internal data mount point failed. Trying manual umount/remount"
                                            mtdDevice="`$bb grep '/dev/' /proc/mounts | $bb grep ' /data ' | $bb awk '{print $1}'`"

                                            if $bb [ ! -z "$mtdDevice" ]; then
                                                doLog d script "Unmounting Internal data from /data"
                                                $bb umount /data || $bb umount -f /data || $bb umount -l /data

                                                if $bb [ -z "`$bb grep ' /data ' /proc/mounts`" ]; then
                                                    doLog d script "Trying to mount Internal data on /sd-ext"
                                                    $bb mount -o rw,nosuid,nodev,noatime,nodiratime $mtdDevice /sd-ext

                                                    if $bb [ -z "`$bb grep ' /sd-ext ' /proc/mounts`" ]; then
                                                        doLog d script "Failed to mount Internal data on /sd-ext, mounting it back on /data"
                                                        $bb mount -o $mtdDevice /data

                                                        if $bb [ ! -z "$lastError" ]; then
                                                            doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                        fi
                                                    fi
                                                fi
                                            fi
                                        fi

                                        if $bb [ ! -z "`$bb grep ' /sd-ext ' /proc/mounts`" ]; then
                                            doLog d script "Internal data was successfully moved from /data into /sd-ext"

                                            doProp set status.destination.internal /sd-ext
                                            doProp set status.destination.external /data

                                            doProp set status.enable_reversed_mount 1

                                        else
                                            doLog e enable_reversed_mount "It was not possible to move the internal data mount point!"
                                            doLog v script "Reversing content options due to r-mount failure in order to keep content in the same locations"

                                            for i in move_apps move_data move_dalvik; do
                                                $bb [ $(doProp get config.$i 0) -eq 0 ] && $(doProp set config.$i 1) || $(doProp set config.$i 0)
                                            done
                                        fi
                                    fi

                                    mountParamsFull="noatime,nodiratime,relatime,noauto_da_alloc,data=ordered,commit=15,barrier=1,nouser_xattr,errors=continue,nosuid,nodev"
                                    mountParamsLimited="noatime,nodiratime,relatime,nosuid,nodev"

                                    doLog d script "Starting mount operating on sd-ext"

                                    for i in $(doProp get status.set_sdext_fstype) auto; do
                                        $bb [ -z "$mountParamsExtras" ] && mp="$mountParamsFull" || mp="$mountParamsFull,$mountParamsExtras"

                                        while :; do
                                            if $bb [ ! -z "$mp" ]; then
                                                doLog d script "Trying to mount sd-ext as %arg1 on %arg2 with options '%arg3'" $i $(doProp get status.destination.external) "$mp"
                                                lastError=$($bb mount -o $mp -t $i $(doProp get status.device.sdcard.partition.sdext) $(doProp get status.destination.external) 2>&1); sync

                                            else
                                                lastError=$($bb mount -t $i $(doProp get status.device.sdcard.partition.sdext) $(doProp get status.destination.external) 2>&1); sync

                                                if $bb [ -z "`$bb cat /proc/mounts | $bb grep -w $(doProp get status.device.sdcard.partition.sdext)`" ]; then
                                                    # Very last change
                                                    $bb mount $(doProp get status.device.sdcard.partition.sdext) $(doProp get status.destination.external); sync
                                                fi
                                            fi

                                            if $bb [ ! -z "`$bb cat /proc/mounts | $bb grep -w $(doProp get status.device.sdcard.partition.sdext)`" ]; then
                                                doLog d script "The sd-ext partition was mounted, now testing writeable state"
                                                $bb echo 1 > $(doProp get status.destination.external)/writeTest
                                                $bb df /sd-ext 2> /dev/null; status=$?

                                                if  $bb [ $status -gt 0 ] || $bb [ ! -f $(doProp get status.destination.external)/writeTest ]; then
                                                    doLog e script "The sd-ext file system type cannot be used as an data partition. Please switch to something like Ext(2/3/4)!"
                                                    mountAction="skip"

                                                    $bb umount $(doProp get status.destination.external)

                                                    break 2
                                                fi

                                                doLog v script "The sd-ext partition was mounted successfully at %arg1" $(doProp get status.destination.external)

                                                $bb rm -rf $(doProp get status.destination.external)/writeTest

                                                if $bb [ ! -z "$mountParamsExtras" ] && ( $bb [ "$mp" != "$mountParamsFull,$mountParamsExtras" ] && $bb [ "$mp" != "$mountParamsLimited,$mountParamsExtras" ] ); then
                                                    doLog w enable_sdext_journal "It was not possible to mount the sd-ext partition without journal!"
                                                fi

                                                break 2

                                            elif $bb [ ! -z "$lastError" ]; then
                                                doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                            fi

                                            if $bb [ ! -z "$mountParamsExtras" ] && [ "$mp" = "$mountParamsFull,$mountParamsExtras" ]; then
                                                doLog d script "The sd-ext partition could not be mounted. Trying again with different mount options"
                                                mp="$mountParamsLimited,$mountParamsExtras"

                                            elif $bb [ "$mp" = "$mountParamsFull" ] || $bb [ "$mp" = "$mountParamsLimited,$mountParamsExtras" ]; then
                                                doLog d script "The sd-ext partition could not be mounted. Trying again with different mount options"
                                                mp="$mountParamsLimited"

                                            elif $bb [ ! -z "$mp" ]; then
                                                doLog d script "The sd-ext partition could not be mounted. Trying again without additional mount options"
                                                mp=
                            
                                            else
                                                break
                                            fi
                                        done

                                        if [ "$i" = "auto" ]; then
                                            break

                                        else
                                            doLog w set_sdext_fstype "Could not mount sd-ext as %arg1. Switching to auto detection!" $i
                                        fi
                                    done

                                    if $bb [ -z "`$bb cat /proc/mounts | $bb grep -w $(doProp get status.device.sdcard.partition.sdext)`" ]; then
                                        doLog e script "The sd-ext partition could not be mounted!"

                                        if $bb [ $(doProp get status.enable_reversed_mount 0) -eq 1 ]; then
                                            doLog w enable_reversed_mount "Moving internal nand data mount point back to /data!"
                                            doProp remove status.enable_reversed_mount

                                            lastError=$($bb mount --move /sd-ext /data 2>&1)

                                            if $bb [ -z "`$bb grep ' /data ' /proc/mounts`" ]; then
                                                doLog d script "Moving Internal data mount point failed. Trying manual umount/remount"
                                                mtdDevice="`$bb grep '/dev/' /proc/mounts | $bb grep ' /sd-ext ' | $bb awk '{print $1}'`"

                                                if $bb [ ! -z "$mtdDevice" ]; then
                                                    doLog d script "Unmounting Internal data from /sd-ext"
                                                    $bb umount /sd-ext || $bb umount -f /sd-ext || $bb umount -l /sd-ext

                                                    if $bb [ -z "`$bb grep ' /sd-ext ' /proc/mounts`" ]; then
                                                        doLog d script "Trying to mount Internal data on /data"
                                                        $bb mount -o rw,nosuid,nodev,noatime,nodiratime $mtdDevice /data

                                                        if $bb [ -z "`$bb grep ' /data ' /proc/mounts`" ]; then
                                                            doLog e script "Could not move Internal data from /sd-ext back to /data"

                                                            if $bb [ ! -z "$lastError" ]; then
                                                                doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                            fi
                                                        fi
                                                    fi
                                                fi
                                            fi
                                        fi

                                        break 2

                                    elif $bb [ $(doProp get status.script_safe_mode 0) -eq 1 ]; then
                                        doLog d script "Safe-mode detected, creating temp symlinks between /sd-ext/app(-*) and /data/app(-*)"

                                        for i in /sd-ext/app/* /sd-ext/app-*/*; do
                                            $bb ln -s $i $($bb echo $i | $bb sed -e 's/^\/sd-ext\//\/data\//') 2> /dev/null
                                        done
                                    fi

                                    doLog v script "Preparing to move content between /data and /sd-ext"

                                    appFolders="app app-private app-system"

                                    $bb [ $(doCheckFolder /data/media) -eq 1 ] && sysFolders="property misc system local tombstones secure media" || sysFolders="property misc system local tombstones secure"

                                    # In Android 2.2+ /data/data is actually /data/user/0
                                    $bb [ $(doCheckFolder /data/user) -eq 1 ] && dataFolders="data user" || dataFolders="data"

                                    for i in /*.rc; do
                                        doRevert="$doRevert $($bb grep mkdir $i | $bb grep -ve '^[ \t]*#' | $bb grep -e ' \/data\/[^\/]* ' | $bb tr -s ' ' | $bb sed 's/mkdir \/data\/\([^ ]*\).*$/\1/' | $bb grep -ve '\(media\|secure\|lost+found\|local\|misc\|system\|tombstones\|property\|data\|dalvik\-\(cache\|system\)\|app\(\-[^ ]*\)*\)$')"
                                        appFolders="$appFolders $($bb grep mkdir $i | $bb grep -ve '^[ \t]*#' | $bb grep -e ' \/data\/app\(\-[^ ]*\)*[^\/]* ' | $bb tr -s ' ' | $bb sed 's/mkdir \/data\/\([^ ]*\).*$/\1/' | $bb grep -ve 'app\(\-system\|\-private\)*$')"
                                    done

                                    externalSize=$(doGetSize /sd-ext)
                                    internalSize=$(doGetSize /data)

                                    $bb [ $(doProp get config.move_data) -eq 1 ] && doMove="$doMove $dataFolders" || doRevert="$doRevert $dataFolders"
                                    $bb [ $(doProp get config.move_dalvik) -eq 1 ] && doMove="$doMove dalvik-cache" || doRevert="$doRevert dalvik-cache"
                                    $bb [ $(doProp get config.move_apps) -eq 1 ] && doMove="$doMove $appFolders" || doRevert="$doRevert $appFolders"
                                    $bb [ $externalSize -lt $internalSize ] && doMoveOrder="revert move revert-retry move-force link" || doMoveOrder="move revert move revert-retry move-force link"

                                    # Failsafe in case r-mount fails, content will stay on the same selected devices
                                    $bb [ $(doProp get status.enable_reversed_mount 0) -eq $(doProp get config.enable_reversed_mount 0) ] && doRevertContent="$doRevert" || doRevertContent="$doMove"
                                    $bb [ $(doProp get status.enable_reversed_mount 0) -eq $(doProp get config.enable_reversed_mount 0) ] && doMoveContent="$doMove" || doMoveContent="$doRevert"
                                    $bb [ $(doProp get status.enable_reversed_mount 0) -eq 1 ] && doMoveContent="$doMoveContent $sysFolders" || doRevertContent="$doRevertContent $sysFolders"

                                    # Remove dupplicates
                                    doRevertContent="`echo $doRevertContent | sed 's/ /\n/g' | awk '!a[$0]++'`"
                                    doMoveContent="`echo $doMoveContent | sed 's/ /\n/g' | awk '!a[$0]++'`"

                                    for action in $doMoveOrder; do
                                        case $action in
                                            revert|revert-retry)
                                                if $bb [ ! -z "$doRevertContent" ]; then
                                                    doHandleContent="$doRevertContent"
                                                    doRevertContent=

                                                    for x in $doHandleContent; do
                                                        doCreateFolder /data/$x

                                                        doLog d script "Looking in %arg1 to see if something should be reverted back to %arg2" /sd-ext/$x /data/$x

                                                        if $bb [ -d /sd-ext/$x ] && $bb [ ! -L /sd-ext/$x ] && $bb [ ! -z "`$bb ls -v /sd-ext/$x | $bb tail -n1`" ] && $bb [ ! -z "`$bb find /sd-ext/$x -type f | $bb tail -n1`" ]; then
                                                            doLog v script "Reverting %arg1 back to %arg2" /sd-ext/$x /data/$x

                                                            xSize="`$bb echo $($bb du -s -m /sd-ext/$x) | $bb awk '{print $1}'`"

                                                            doLog d script "The size of %arg1 is %arg3. Comparing it to the remaining spaze on %arg2 which is %arg4" /sd-ext/$x /data ${xSize}Mb ${internalSize}Mb

                                                            if $bb [ $internalSize -gt $xSize ]; then
                                                                if $bb [ "$x" != "dalvik-cache" ]; then
                                                                    for i in /sd-ext/$x/*; do
                                                                        ii="`$bb basename $i`"

                                                                        if $bb [ ! -L /sd-ext/$x/$ii ] || ( $bb [ ! -f /data/$x/$ii ] && $bb [ ! -d /data/$x/$ii ] ); then
                                                                            if $bb [ -e /data/$x/$ii ]; then
                                                                                $bb rm -rf /data/$x/$ii
                                                                            fi

                                                                            $bb mv -f /sd-ext/$x/$ii /data/$x/

                                                                        else
                                                                            $bb rm -rf /sd-ext/$x/$ii
                                                                        fi
                                                                    done

                                                                    xSize=$($bb echo $($bb du -s -m /data/$x) | $bb awk '{print $1}')

                                                                    ( $bb [ -d /sd-ext/$x ] && $bb [ ! -z "`$bb ls -v /sd-ext/$x | $bb tail -n1`" ] && $bb [ ! -z "`$bb find /sd-ext/$x -type f | $bb tail -n1`" ] ) && attention="$attention ${x}:revert:notempty" || $bb rm -rf /sd-ext/$x

                                                                else
                                                                    $bb rm -rf /sd-ext/$x
                                                                fi

                                                                internalSize=$(($internalSize - $xSize))
                                                                externalSize=$(($externalSize + $xSize))

                                                            elif $bb [ "$action" = "revert-retry" ]; then
                                                                doLog d script "Could not revert %arg1 do to low storage on %arg2. Giving up" /sd-ext/$x /data
                                                                doMoveContent="$doMoveContent $x"
                                                                attention="$attention ${x}:revert:size"

                                                            else
                                                                doLog d script "Could not revert %arg1 do to low storage on %arg2. Trying again later" /sd-ext/$x /data
                                                                doRevertContent="$doRevertContent $x"
                                                            fi

                                                        elif $bb [ -e /sd-ext/$x ]; then
                                                            $bb rm -rf /sd-ext/$x
                                                        fi
                                                    done
                                                fi
                                            ;;

                                            move|move-force)
                                                if $bb [ ! -z "$doMoveContent" ]; then
                                                    doHandleContent="$doMoveContent"
                                                    doMoveContent=

                                                    for x in $doHandleContent; do
                                                        doCreateFolder /data/$x 1

                                                        doLog d script "Looking in %arg1 to see if something should be moved into %arg2" /data/$x /sd-ext/$x

                                                        if $bb [ -d /data/$x ] && $bb [ ! -z "`$bb ls -v /data/$x | $bb tail -n1`" ] && $bb [ ! -z "`$bb find /data/$x -type f | $bb tail -n1`" ]; then
                                                            doLog v script "Moving content from %arg1 to %arg2" /data/$x /sd-ext/$x

                                                            xSize="`$bb echo $($bb du -s -m /data/$x) | $bb awk '{print $1}'`"

                                                            doLog d script "The size of %arg1 is %arg3. Comparing it to the remaining spaze on %arg2 which is %arg4" /data/$x /sd-ext ${xSize}Mb ${externalSize}Mb

                                                            if $bb [ $externalSize -gt $xSize ]; then
                                                                if $bb [ "$x" != "dalvik-cache" ]; then
                                                                    for i in /data/$x/*; do
                                                                        ii="`$bb basename $i`"

                                                                        if $bb [ ! -L /data/$x/$ii ] || ( $bb [ ! -f /sd-ext/$x/$ii ] && $bb [ ! -d /sd-ext/$x/$ii ] ); then
                                                                            if $bb [ -e /sd-ext/$x/$ii ]; then
                                                                                $bb rm -rf /sd-ext/$x/$ii
                                                                            fi

                                                                            $bb mv -f /data/$x/$ii /sd-ext/$x/

                                                                            if $bb [ $(doProp get status.script_safe_mode 0) -eq 1 ]; then
                                                                                # The system may boot before init.d is done and we need the package manager to register all the apps
                                                                                $bb ln -sf /sd-ext/$x/$ii /data/$x/$ii
                                                                            fi
                                                                        fi
                                                                    done

                                                                    xSize=$($bb echo $($bb du -s -m /sd-ext/$x) | $bb awk '{print $1}')

                                                                    ( $bb [ -d /data/$x ] && $bb [ ! -z "`$bb ls -v /data/$x | $bb tail -n1`" ] && $bb [ ! -z "`$bb find /data/$x -type f | $bb tail -n1`" ] ) && attention="$attention ${x}:move:notempty"

                                                                else
                                                                    $bb rm -rf /data/$x/*
                                                                fi

                                                                externalSize=$(($externalSize - $xSize))
                                                                internalSize=$(($internalSize + $xSize))

                                                                doLinkContent="$doLinkContent $x"

                                                            elif $bb [ "$action" = "move-force" ]; then
                                                                doLog d script "Could not move %arg1 do to low storage on %arg2. Giving up" /data/$x /sd-ext
                                                                attention="$attention ${x}:move:size"

                                                            else
                                                                doLog d script "Could not move %arg1 do to low storage on %arg2. Trying again later" /data/$x /sd-ext
                                                                doMoveContent="$doMoveContent $x"
                                                            fi

                                                        else
                                                            doLinkContent="$doLinkContent $x"
                                                        fi
                                                    done
                                                fi
                                            ;;

                                            link)
                                                if $bb [ ! -z "$attention" ]; then
                                                    for x in $attention; do
                                                        case $($bb echo $x | $bb cut -d ':' -f1 | $bb cut -d '-' -f1) in
                                                            app) reporter="move_apps" ;;
                                                            dalvik) reporter="move_dalvik" ;;
                                                            data|user) reporter="move_data" ;;
                                                            *) reporter="log" ;;
                                                        esac

                                                        if $bb [ "`$bb echo $x | $bb cut -d ':' -f2`" = "move" ]; then
                                                            $bb [ "`$bb echo $x | $bb cut -d ':' -f3`" = "size" ] && doLog e $reporter "The content of %arg1 is to big to be moved to %arg2!" /data/$($bb echo $x | $bb cut -d ':' -f1) sd-ext || doLog e $reporter "Not everything from %arg1 could be moved to %arg2. Check available disk space!" /data/$($bb echo $x | $bb cut -d ':' -f1) /sd-ext/$($bb echo $x | $bb cut -d ':' -f1)

                                                        else
                                                            $bb [ "`$bb echo $x | $bb cut -d ':' -f3`" = "size" ] && doLog e $reporter "The content of %arg1 is to big to be reverted back to %arg2!" /sd-ext/$($bb echo $x | $bb cut -d ':' -f1) data || doLog e $reporter "Not everything from %arg1 could be reverted back to %arg2. Check available disk space!" /sd-ext/$($bb echo $x | $bb cut -d ':' -f1) /data/$($bb echo $x | $bb cut -d ':' -f1)
                                                        fi
                                                    done
                                                fi

                                                if $bb [ ! -z "$doLinkContent" ]; then
                                                    for x in $doLinkContent; do
                                                        doLinkContent=

                                                        # Do some cleanup
                                                        if $bb [ $(doProp get status.script_safe_mode 0) -eq 1 ] && $bb [ "$($bb echo $x | $bb cut -d '-' -f1)" = "app" ]; then
                                                            doLog d script "Safe-mode detected, cleaning up some unused symlinks"

                                                            for i in /data/$x/*; do
                                                                if $bb [ -L $i ] && $bb [ ! -e $($bb readlink -f $i) ]; then
                                                                    $bb rm -rf $i
                                                                fi
                                                            done
                                                        fi

                                                        doLog v script "Attaching %arg1 to %arg2" /sd-ext/$x /data/$x
                                                        lastError=$($bb mount --bind /sd-ext/$x /data/$x 2>&1)

                                                        if $bb [ ! -z "`$bb grep " /data/$x " /proc/mounts`" ] || $bb [ ! -z "`$bb grep " /sd-ext/$x " /proc/mounts`" ]; then
                                                            case $($bb echo $x | $bb cut -d '-' -f1) in
                                                                app) doProp set status.move_apps 1 ;;
                                                                dalvik) doProp set status.move_dalvik 1 ;;
                                                                data|user) doProp set status.move_data 1 ;;
                                                            esac

                                                        else
                                                            case $($bb echo $x | $bb cut -d '-' -f1) in
                                                                app) reporter="move_apps" ;;
                                                                dalvik) reporter="move_dalvik" ;;
                                                                data|user) reporter="move_data" ;;
                                                                *) reporter="log" ;;
                                                            esac

                                                            doLog e $reporter "It was not possible to link %arg1 to %arg2!" /sd-ext/$x /data/$x

                                                            if $bb [ ! -z "$lastError" ]; then
                                                                doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                            fi
                                                        fi
                                                    done
                                                fi
                                            ;;
                                        esac
                                    done
 
                                    if $bb [ $(doProp get status.enable_reversed_mount 0) -eq 1 ]; then
                                        # Make sure that important sub-folders from init.rc exists. Android 4.x will create issues if they do.
                                        for x in /*.rc; do
                                            doCreate="$doCreate $($bb grep mkdir $x | $bb grep -e ' \/data\/[^\/]*\(\/[^\/]*\)* ' | $bb tr -s ' ' | $bb sed 's/mkdir \(\/data\/[^ ]*\).*$/\1/')"
                                        done

                                        doCreate="`echo $doCreate | sed 's/ /\n/g' | awk '!a[$0]++'`"

                                        for i in $doCreate; do
                                            doLog d script "Making sure that the init.rc defined folder %arg1 exists" $i
                                            doCreateFolder $i
                                        done
                                    fi

                                    # Android 4.2 has some hidden dependencies that it will not re-create of it's own. This is of cause for r-mount
                                    doRevert="`$bb ls -av /sd-ext | $bb grep -e '^\.' | $bb grep -ve '^[\.]*$'`"
                                    for i in $doRevert; do
                                        doLog d script "Reverting %arg1 back to %arg2" $i /data/
                                        $bb mv -f $i /data/
                                    done

                                    break 2
                                fi
                            done

                            if $bb [ $mmcTries -gt 7 ]; then
                                    doLog e script "Timedout while searching for the sd-ext partition!"; break

                            else
                                    $bb sleep 1
                            fi
                        done

                        doLog v script "Optimizing the internal nand partitions"

                        for i in /system $(doProp get status.destination.internal /data) /cache; do
                                mtdDevice="`$bb grep '/dev/' /proc/mounts | $bb grep " $i " | $bb awk '{print $1}'`"

                                doLog d script "Located the device %arg1 belonging to %arg2" $mtdDevice $i

                                if $bb [ -b $mtdDevice ]; then
                                        mtdMM="`$bb ls -l $mtdDevice | $bb tr -s ' ' | $bb sed -ne 's/^.*[ ]\([0-9]*\),[ ]\([0-9]*\)[ ].*$/\1:\2/p'`"

                                        doLog d script "Located the device MM number %arg1 belonging to %arg2" $mtdMM $i

                                        if $bb [ -e /sys/devices/virtual/bdi/$mtdMM/read_ahead_kb ]; then
                                                doLog v script "Setting %arg1 nand readahead to 4kb" $i
                                                $bb echo 4 > /sys/devices/virtual/bdi/$mtdMM/read_ahead_kb
                                        fi

                                        doLog v script "Setting optimized mount parameters on %arg1" $i
                                        $bb mount -o remount,noatime,nodiratime,relatime $i

                                else
                                        doLog w script "Could not locate the device file for %arg1" $i
                                fi
                        done

                        $bb sync

                        doLog v script "Looking for new system apps in %arg1 to link to %arg2" /data/app-system /system/app

                        # Do an S-Off test
                        doLog d script "Running S-On test on /system"
                        $bb touch /system/s-off 2> /dev/null

                        if $bb [ -e /system/s-off ]; then
                            $bb rm -rf /system/s-off

                            for x in /system/app/*; do
                                if $bb [ -L $x ] && $bb [ ! -e "`$bb readlink $x`" ]; then
                                    $bb rm -rf $x
                                fi
                            done

                            if $bb [ -d /data/app-system ] && $bb [ ! -z "`$bb ls -v /data/app-system`" ]; then
                                for x in /data/app-system/*; do
                                    doLog d script "Checking system link on %arg1" $x

                                    y="`$bb basename $x`"

                                    if $bb [ ! -e /system/app/$y ] || $bb [ ! -L /system/app/$y ]; then
                                        $bb [ -e /system/app/$y ] && $bb rm -rf /system/app/$y

                                        doLog v script "Creating link for %arg1 in %arg2" $($bb basename $x) /system/app/
                                        $bb ln -s $x /system/app/
                                    fi
                                done
                            fi

                        else
                            doLog d script "The /system partition is S-On protected"

                            if $bb [ -d /data/app-system ] && $bb [ ! -z "`$bb ls -v /data/app-system`" ]; then
                                doLog w script "Cannot handle app links from %arg1 to %arg2 on S-On devices!" /data/app-system /system/app
                            fi
                        fi

                        doLog d script "Checking SWAP partition and SWAP settings"

                        if $bb [ -e /proc/sys/vm/swappiness ] && $bb [ ! -z "`doProp get status.device.sdcard.partition.swap`" ] && $bb [ $(doProp get config.enable_swap) -eq 1 ]; then
                                doLog v script "Activating SWAP partition"
                                lastError=$($bb swapon $(doProp get status.device.sdcard.partition.swap) 2>&1)

                                if $bb [ "$?" = "0" ]; then
                                        doProp set status.enable_swap 1

                                        doLog v script "Setting swappiness value to '%arg1'" $(doProp get config.set_swap_level 0)
                                        echo $(doProp get config.set_swap_level 0) > /proc/sys/vm/swappiness

                                        if $bb [ "$(doProp get config.set_swap_level 0)" != "`$bb cat /proc/sys/vm/swappiness`" ]; then
                                            doLog w set_swap_level "The swappiness value could not be changed!"
                                        fi

                                        doProp set status.set_swap_level $($bb cat /proc/sys/vm/swappiness)

                                else
                                        doLog e enable_swap "Could not activate the SWAP partition!"
                                        echo 0 > /data/property/m2ds.enable_swap

                                        if $bb [ ! -z "$lastError" ]; then
                                            doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                        fi
                                fi

                        elif $bb [ ! -e /proc/sys/vm/swappiness ] && $bb [ $(doProp get config.enable_swap) -eq 1 ]; then
                            doLog w enable_swap "You kernel does not support SWAP partitions!"

                        elif $bb [ -z "`doProp get status.device.sdcard.partition.swap`" ] && $bb [ $(doProp get config.enable_swap) -eq 1 ]; then
                            doLog w enable_swap "Did not find any SWAP partition!"
                            echo 0 > /data/property/m2sd.enable_swap
                        fi

                        for loopCachewrapper in true; do
                            doLog d script "Handling the Cache partition and it's settings"

                            if $bb [ $(doProp get config.enable_cache) -eq 1 ] || ( $bb [ $(doProp get config.enable_cache) -eq 2 ] && $bb [ $(doGetSize /cache) -lt 40 ] ); then
                                doLog v script "Preparing to replace the cache partition"

                                externalDestination=$(doProp get status.destination.external /sd-ext)
                                internalDestination=$(doProp get status.destination.internal /data)

                                $bb [ ! -z "`$bb cat /proc/mounts | $bb grep -w $(doProp get status.device.sdcard.partition.sdext /sd-ext)`" ] && externalSize=$(doGetSize $externalDestination) || externalSize=0
                                internalSize=$(doGetSize $internalDestination)

                                if $bb [ ! -z "`$bb grep ' /sd-ext ' /proc/mounts`" ] && ( $bb [ $externalSize -ge 128 ] || $bb [ $(doProp get config.no_tmpfs_cache) -eq 1 ] ) && $bb [ $externalSize -gt $internalSize ]; then
                                        doLog d script "Setting cache location to %arg1" $externalDestination/cache
                                        cacheLocation="$externalDestination/cache"

                                elif $bb [ $internalSize -ge 128 ] || $bb [ $(doProp get config.no_tmpfs_cache) -eq 1 ]; then
                                        doLog d script "Setting cache location to %arg1" $internalDestination/cache
                                        cacheLocation="$internalDestination/cache"

                                else
                                        doLog d script "Setting cache location to %arg1" "/cache (tmpfs)"
                                        cacheLocation="tmpfs"
                                fi

                                for i in $externalDestination/cache $internalDestination/cache; do
                                    if $bb [ "$i" != "$cacheLocation" ] && $bb [ -d $i ]; then
                                            $bb rm -rf $i

                                    elif $bb [ ! -d $i ]; then
                                            $bb mkdir $i
                                            $bb chown 1000.2001 $i
                                            $bb chmod 0771 $i
                                    fi
                                done

                                if $bb [ -z "`grep dalvik.vm.dexopt-data-only=1 /system/build.prop`" ] && $bb [ $(doCheckFolder /cache/dalvik-cache) -eq 1 ]; then
                                    if $bb [ $(doProp get status.script_safe_mode) -eq 1 ]; then
                                        if $bb [ $(doProp config.enable_cache) -eq 1 ]; then
                                            doLog w enable_cache "Cannot handle cache with CM's %arg1 on systems running in safe-mode!" /cache/dalvik-cache
                                        fi

                                        doLog d script "Safe-mode detected with CM %arg1, skipping cache configurations" /cache/dalvik-cache

                                        break
                                    fi

                                    doCreateFolder /internal-cache

                                    doLog d script "Moving Internal cache mount point from %arg1 to %arg2" /cache /internal-cache
                                    lastError=$($bb mount --move /cache /internal-cache 2>&1)

                                    if $bb [ -z "`$bb grep ' /internal-cache ' /proc/mounts`" ]; then
                                        doLog d script "Moving Internal cache mount point failed. Trying manual umount/remount"
                                        mtdDevice="`$bb grep '/dev/' /proc/mounts | $bb grep ' /cache ' | $bb awk '{print $1}'`"

                                        doLog d script "Unmounting Internal cache from %arg1" /cache
                                        $bb umount /cache || $bb umount -f /cache || $bb umount -l /cache

                                        if $bb [ -z "`$bb grep ' /cache ' /proc/mounts`" ]; then
                                            doLog d script "Trying to mount Internal cache on %arg1" /internal-cache
                                            $bb mount $mtdDevice /internal-cache

                                            if $bb [ -z "`$bb grep ' /internal-cache ' /proc/mounts`" ]; then
                                                doLog e enable_cache "Could not move Internal cache from %arg1 to %arg2" /cache /internal-cache

                                                if $bb [ ! -z "$lastError" ]; then
                                                    doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                                fi

                                                break
                                            fi

                                        else
                                            doLog e enable_cache "Could not move Internal cache from %arg1 to %arg2" /cache /internal-cache

                                            break
                                        fi
                                    fi

                                    if $bb [ ! -z "`$bb grep ' /internal-cache ' /proc/mounts`" ]; then
                                        doLog v script "The internal cache was successfully moved to %arg1" /internal-cache
                                    fi

                                else
                                    doLog v script "Unmounting internal cache partition"
                                    $bb umount /cache
                                fi

                                doLog v script "Attaching %arg1 to %arg2" $cacheLocation /cache
                                if $bb [ "$cacheLocation" = "tmpfs" ]; then
                                     lastError=$($bb mount -t tmpfs -o rw,nosuid,nodev,noatime,nodiratime,relatime,mode=0771,uid=1000,gid=2001 tmpfs /cache 2>&1)
                                else
                                     lastError=$($bb mount --bind $cacheLocation /cache 2>&1)
                                fi

                                if $bb [ ! -z "`$bb grep ' /cache ' /proc/mounts`" ] || ( $bb [ "$cacheLocation" != "tmpfs" ] && $bb [ ! -z "`$bb grep " $cacheLocation " /proc/mounts`" ] ); then
                                    doProp set status.enable_cache 1

                                    doSetPerms /cache 1000.2001 0771

                                    if $bb [ "$cacheLocation" = "tmpfs" ]; then
                                        doLog v destination.cache "Cache has been mounted as tmpfs"
                                        doProp set status.destination.cache /cache

                                    else
                                        doProp set status.destination.cache $cacheLocation
                                    fi

                                    for x in /*.rc; do
                                        doCreate="$doCreate $($bb grep mkdir $x | $bb grep -e ' \/cache\/[^\/]*\(\/[^\/]*\)* ' | $bb tr -s ' ' | $bb sed 's/mkdir \(\/cache\/[^ ]*\).*$/\1/')"
                                    done

                                    doCreate="`echo $doCreate | sed 's/ /\n/g' | awk '!a[$0]++'`"

                                    for i in $doCreate; do
                                        doLog d script "Making sure that the init.rc defined folder %arg1 exists" $i
                                        doCreateFolder $i
                                    done

                                    if $bb [ -z "`grep dalvik.vm.dexopt-data-only=1 /system/build.prop`" ] && $bb [ $(doCheckFolder /cache/dalvik-cache) -eq 1 ]; then
                                        doLog v script "Attaching %arg1 to %arg2" /internal-cache/dalvik-cache $(doProp get status.destination.cache /cache)/dalvik-cache
                                        $bb rm -rf $(doProp get status.destination.cache /cache)/dalvik-cache/*
                                        lastError=$($bb mount --bind /internal-cache/dalvik-cache $(doProp get status.destination.cache /cache)/dalvik-cache 2>&1)

                                        if $bb [ -z "`$bb grep ' /cache/dalvik-cache ' /proc/mounts`" ] && $bb [ -z "`$bb grep ' /internal-cache/dalvik-cache ' /proc/mounts`" ] && $bb [ -z "`$bb grep " $(doProp get status.destination.cache /cache)/dalvik-cache " /proc/mounts`" ]; then
                                            doLog w enable_cache "Could not attach CM's %arg1 to %arg2" /cache/dalvik-cache $(doProp get status.destination.cache /cache)/dalvik-cache
                                            $bb rm -rf /internal-cache/dalvik-cache/*

                                            if $bb [ ! -z "$lastError" ]; then
                                                doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                            fi

                                        else
                                            # Be very sure that these perms are as they should or you will end up with a lot of FC
                                            doSetPerms /cache/dalvik-cache 1000.1000 0771
                                        fi
                                    fi

                                 else
                                    doLog e enable_cache "It was not possible to attach %arg1 to %arg2!" $cacheLocation /cache
                
                                    if $bb [ -z "`grep dalvik.vm.dexopt-data-only=1 /system/build.prop`" ] && $bb [ $(doCheckFolder /cache/dalvik-cache) -eq 1 ]; then
                                        $bb umount /internal-cache && $bb mount /cache

                                    else
                                        $bb mount /cache
                                    fi

                                    if $bb [ ! -z "$lastError" ]; then
                                        doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                    fi
                                 fi

                            elif $bb [ $(doProp get config.enable_cache) -eq 2 ]; then
                                doLog d script "The cache stettings are set to auto and internal cache storage is %arg1, leaving cache untouched" $(doGetSize /cache)Mb

                            else
                                doLog d script "The cache stettings are disabled, leaving cache untouched"
                            fi

                            break
                        done

                        doLog d script "Examining how to handle %arg1" /data/data/com.android.providers.downloads/cache
                        if $bb [ -d /data/data/com.android.providers.downloads/cache ]; then
                            $bb [ $(doProp get status.move_data 0) -eq 1 ] && dataLoc=/sd-ext || dataLoc=/data
                            $bb [ $(doProp get status.move_data 0) -eq 1 ] && extLoc=/data || extLoc=/sd-ext

                            $bb [ ! -z "`$bb cat /proc/mounts | $bb grep "$extLoc "`" ] && extSize=$(doGetSize $extLoc) || extSize=0
                            dataSize=$(doGetSize $dataLoc)

                            if $bb [ $(doProp get config.disable_cache_folders) -eq 0 ] && $bb [ $extSize -gt $dataSize ]; then
                                if $bb [ ! -d $extLoc/data@providers.downloads@cache ]; then
                                    $bb mkdir $extLoc/data@providers.downloads@cache
                                    $bb chmod 0777 $extLoc/data@providers.downloads@cache
                                    $bb chown 2000.2000 $extLoc/data@providers.downloads@cache
                                fi

                                if $bb [ -d $dataLoc/data@providers.downloads@cache ]; then
                                    $bb rm -rf $dataLoc/data@providers.downloads@cache
                                fi

                                doLog v script "Attaching %arg1 on %arg2" $dataLoc/data/com.android.providers.downloads/cache $externalDestination/data@providers.downloads@cache
                                lastError=$($bb mount --bind $extLoc/data@providers.downloads@cache $dataLoc/data/com.android.providers.downloads/cache 2>&1)

                                if $bb [ -z "`$bb busybox grep $dataLoc/data/com.android.providers.downloads/cache /proc/mounts`" ] && $bb [ -z "`$bb busybox grep $extLoc/data@providers.downloads@cache /proc/mounts`" ]; then
                                    doLog w script "Could not attach %arg1 on %arg2" $dataLoc/data/com.android.providers.downloads/cache $extLoc/data@providers.downloads@cache

                                    if $bb [ ! -z "$lastError" ]; then
                                        doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                    fi
                                fi

                            else
                                for i in /data/data@providers.downloads@cache /sd-ext/data@providers.downloads@cache; do
                                    if $bb [ -d $i ]; then
                                        $bb rm -rf $i
                                    fi
                                done

                                doLog v script "Changing permissions on %arg1" /data/data/com.android.providers.downloads/cache
                                $bb chmod 0777 /data/data/com.android.providers.downloads/cache
                            fi
                        else
                            doLog d script "The cache folder %arg1 is not available. Trying again on next boot" /data/data/com.android.providers.downloads/cache
                        fi

                        doLog v script "Changing permissions on %arg1" /data/local/tmp
                        if $bb [ ! -d /data/local/tmp ]; then
                            $bb mkdir -p /data/local/tmp
                        fi

                        $bb chmod 0777 /data/local/tmp
                        $bb chown 2000.2000 /data/local/tmp

                        $bb [ ! -z "`$bb cat /proc/mounts | $bb grep "/sd-ext "`" ] && extSize=$(doGetSize /sd-ext) || extSize=0
                        dataSize=$(doGetSize /data)

                        if $bb [ $(doProp get config.disable_cache_folders) -eq 0 ] && $bb [ $extSize -gt $dataSize ]; then
                            if $bb [ ! -d /sd-ext/data@local@tmp ]; then
                                $bb mkdir /sd-ext/data@local@tmp
                                $bb chmod 0777 /sd-ext/data@local@tmp
                                $bb chown 2000.2000 /sd-ext/data@local@tmp
                            fi

                            doLog v script "Attaching %arg1 on %arg2" /data/local/tmp /sd-ext/data@local@tmp
                            lastError=$($bb mount --bind /sd-ext/data@local@tmp /data/local/tmp 2>&1)

                            if $bb [ -z "`$bb grep /data/local/tmp /proc/mounts`" ] && $bb [ -z "`$bb grep /sd-ext/data@local@tmp /proc/mounts`" ]; then
                                doLog w script "Could not attach %arg1 on %arg2" /data/local/tmp /sd-ext/data@local@tmp

                                if $bb [ ! -z "$lastError" ]; then
                                    doLog d script "Shell Error Message: [%arg1 ...]" "$($bb echo $lastError | $bb awk '{print substr($0, 0, 150)}')"
                                fi
                            fi

                        else
                            if $bb [ -d /sd-ext/data@local@tmp ]; then
                                $bb rm -rf /sd-ext/data@local@tmp
                            fi
                        fi

                        doProp set status.script 1
                    ;;
                esac
            fi

	        $bb [ "$modRoot" != "rw" ] && $bb mount -o remount,ro /
	        $bb [ "$modSystem" != "rw" ] && $bb mount -o remount,ro /system
        ;;
    esac

    break

done

if [ ! -z "$doKillPid" ]; then
    doLog v script "Restarting System Server"

    $bb kill -9 $doKillPid
fi
